### ISSUE TITLE
汉字文件名 图片外链生成错误

### ISSUE THREAD

**Issue by misakar** [bHps2016/Drag#3]
生成的外链: http://7xj431.com1.z0.glb.clouddn.com/屏幕快照 20202016-11-10 2020下午6.41.12.png
![](http://7xj431.com1.z0.glb.clouddn.com/屏幕快照 20202016-11-10 2020下午6.41.12.png
)
正确的外链应该是转义过的: http://7xj431.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-11-10%20%E4%B8%8B%E5%8D%886.41.12.png
![](http://7xj431.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-11-10%20%E4%B8%8B%E5%8D%886.41.12.png)

貌似因为含空格

**Comment by misakar** [comment]
补充
- 文件名: 屏幕快照 2016-11-10 下午6.41.12.png

**Comment by shengxihu** [comment]
Fixed!

**Comment by misakar** [comment]
thx😄
